### ISSUE TITLE
get annotation on wrong element

### ISSUE THREAD

**Issue by evant** [android/kotlin#108]
With the code
```kotlin
class Foo(@get:Annotation val bar: Bar)
```
I would expect the annotation to be present on `declaration.getter.annotations` but it's on `declaration.annotations` instead.

**Comment by neetopia** [comment]
#118 included a fix. Not directly fixing your use case but now you are able to get such annotation for the property itself. Reason for doing so is to avoid confusing other platforms as quite an amount of annotation use-site targets are JVM platform specific.
