### ISSUE TITLE
Mutability of the property from constructor

### ISSUE THREAD

**Issue by kamilr12** [android/kotlin#109]
Is there any way to access the mutability of the property from the primary constructor, for example get boolean ```isVar``` from ```arg1``` in this code snippet

```class A(val arg1: Int)```

I have tried ```KSPropertyDeclaration``` but I wasn't able to find this feature.

Is there any feature like ```KSPropertyDeclaration#isMutable()```?

**Comment by neetopia** [comment]
One way to do so is try to get the `getter` of a property declaration, if null then it is immutable.

**Comment by neetopia** [comment]
I will update the comment in KSPropertyDeclaration to indicate that.

**Comment by neetopia** [comment]
Actually properties declared in interface does not have accessors but can still be mutable.. Adding `isMutable` API to KSPropertyDeclaration is the way to go.

**Comment by neetopia** [comment]
some small change to original proposal: named API to `isVar`
