### ISSUE TITLE
Generic types in KSType or KSTypeReference

### ISSUE THREAD

**Issue by kamilr12** [android/kotlin#111]
Is there any way to tell that ```KSType``` for example ```returnType``` of ```KSFunctionDeclaration``` is the generic type?

How to differentiate this one:

```fun foo(): Int```

from this one

```fun <T> genericFunction(arg: T): T```

**Comment by neetopia** [comment]
You can use `KSType.declaration` to determine that, if it is a generic type, you will get a KSTypeParameter as the result.

**Comment by kamilr12** [comment]
Thank you!
