### ISSUE TITLE
resolve() on annotationType is returning null

### ISSUE THREAD

**Issue by evant** [android/kotlin#126]
For the code:
```kotlin
class Foo(@get:Bar val bar: Bar)
```
```kotlin
barProperty.annotations[0].annotationType.resolve()
```
is returning null on version 20200828. This was working in 20200814.

As an aside: I'm only resolving the annotation type to get the fully qualified annotation name. Don't know if there is/should be a better way to check an annotation is of the expected type.

**Comment by neetopia** [comment]
comparing resolved type with FQN should be fine, I would also do that to determine if an annotation has a specific type.

**Comment by neetopia** [comment]
This issue seems to be introduce by #119 . It looks like resolved type is not written into BindingContext. The strange part is if I do `resolveDeclaration` in IDE with evaluate expression, it will be stored into binding context correctly..  cc @ting-yuan

**Comment by neetopia** [comment]
#130 include a workaround.
