### ISSUE TITLE
Investigate local scope for annotation entry

### ISSUE THREAD

**Issue by davidjwiner** [android/kotlin#14]
See TODO in KSAnnotationImpl.

**Comment by ting-yuan** [comment]
@neetopia I cannot find the TODO in KSAnnotationImpl. Could you elaborate?

**Comment by ting-yuan** [comment]
This is probably referring to `// TODO: local scope` of `KtElement.findLexicalScope()`, which is only used in `resolveAnnotationEntry`, which is only used in `KSAnnotationImpl`. It was already addressed by eed04e4bfd70d80be1e9b7fdf1c39b5db0c39ea6.
