### ISSUE TITLE
Caching for KSTypeReferenceJavaImpl is not working correctly

### ISSUE THREAD

**Issue by neetopia** [android/kotlin#41]
Reproduce:

class A {
    public List<? extends Set> extendsSetFun() {}

    public List<? extends List> extendsListFun() {}
}

Two functions' return type will be same KSTypeReferenceJavaImpl, despite difference in type argument. My guess is PsiType didn't calculate hash based on type argument.

**Comment by neetopia** [comment]
Also the implementation in KSTypeImpl is not taking type arguments into account. 

CC @ting-yuan

**Comment by ting-yuan** [comment]
`KSTypeImpl.arguments` is optional. It is only a convenient way to get the corresponding elements. If not supplied, they'll be computed via KotlinType on demand.

**Comment by neetopia** [comment]
Actually can't reproduce it now, close for now.
