### ISSUE TITLE
API to check if a function has default implementation

### ISSUE THREAD

**Issue by yigit** [android/kotlin#49]
As far as I can see, there is no way to check if a `KSFunctionDeclaration` has a default implementation.

As Room generates Java code, when creating the implementation for a Dao interface, we have to generate the implementation that delegates to the default implementation so this is necessary for room.

Even if Room was generating kotlin code, we would still need this functionality as we have to print an error if a function in dao is not annotated properly. For that case, interface methods with default implementations are OK.

e.g.

```
@Dao
interface MyDao {
    @Query("select * from foo")
    fun goodQuery():List<Foo>

   fun okMethod() {
       
   }

   @Transaction
   fun transactionMethod() {
        // room will override this to be called inside a database transaction
   }

   // method without implementation nor any room annotations so we need to throw an error
   fun badMethod()
    
}

```

**Comment by neetopia** [comment]
It looks to me that providing an isAbstract() API for functions would help.

On a side note, I tried to generate the kapt stub from the code snippet you provided, what I got is 
```
public abstract interface InterfaceWithDefault {
    
    @Transaction()
    public abstract int transactionMethod();
    
    public abstract void badMethod();
    
    @kotlin.Metadata(mv = {1, 1, 18}, bv = {1, 0, 3}, k = 3)
    public final class DefaultImpls {
        
        @Transaction()
        public static int transactionMethod(InterfaceWithDefault $this) {
            return 0;
        }
    }
}
```
It looks to me that if you inspect @Transaction annotated method you are still getting a method without default implementation, but the annotation is also carried into DefaultImpls nested class for delegating the default implementation. Is there any logic in Room that take care of such stubs?

**Comment by ZacSweers** [comment]
Those wouldn’t be visible in stubs because DefaultImpls is a synthetic class (which aren’t visible in the elements API). Would be interesting to see how it looks with `@JvmDefault` though

**Comment by yigit** [comment]
yep, thats what room literally does:

https://cs.android.com/androidx/platform/frameworks/support/+/androidx-master-dev:room/compiler/src/main/kotlin/androidx/room/ext/element_ext.kt;l=372?q=element_ext.kt

We find the enclosing class with name `DefaultImpls` and check for its methods

**Comment by neetopia** [comment]
#55
