### ISSUE TITLE
Annotation with `Class[]` member always returns an empty list

### ISSUE THREAD

**Issue by ZacSweers** [android/kotlin#5]
I've been trying to write a prototype of AutoService via KSP, and notice that the `value` field (a `Class` array) always returns an empty list when I try to query the annotation value in KSP

Repro branch: https://github.com/ZacSweers/moshi-sealed/tree/z/ksp

Under `AutoServiceKsProcessor.kt`, there's a println with a comment where it finds an empty list

![image](https://user-images.githubusercontent.com/1361086/84326025-1404a600-ab4a-11ea-8979-c226d0b2b3c9.png)

**Comment by ting-yuan** [comment]
A patch to #13 is on the way: #29 

However, there is one more problem. The empty list here is actually a symptom of the failure to resolve `SymbolProcessor` in the annotation. I'm still investigating.

**Comment by ting-yuan** [comment]
Fixed in [1.4-M1-dev-experimental-20200626](https://github.com/android/kotlin/tree/1.4-M1-dev-experimental-20200626)
