### ISSUE TITLE
API to check if property has a default implmenntation

### ISSUE THREAD

**Issue by evant** [android/kotlin#69]
This is similar to #49, the same thing applies to properties as well. Right know you can't distinguish between:

```kotlin
interface Foo {
  val bar: Int get() = 1
}
```
and
```kotlin
interface Foo {
   val bar: Int
}
```

Adding `isAbstract` to `KSPropertyDeclaration` as well should work.

**Comment by neetopia** [comment]
Actually I have thought about adding isAbstract to KSPropertyDeclaration in #55 
I can definitely do this, just wonder if there is a practical usage for this though

**Comment by evant** [comment]
In my case I want to treat abstract properties and functions the same way. So the consumer can either do:

```kotlin
@MyAnnotation
interface Foo {
  fun foo(): Int
  fun bar(): Int = ...
}
```
generates:
```kotlin
class FooImpl : Foo {
   override fun foo(): Int = ...
}
```
or
```kotlin
@MyAnnotation
interface Foo {
  val foo: Int
  val bar: Int get() = ...
}
```
generates:
```kotlin
class FooImpl : Foo {
   override val foo: Int get() = ...
}
```
