### ISSUE TITLE
createNewFile generates trailing period if extension is empty

### ISSUE THREAD

**Issue by ZacSweers** [android/kotlin#70]
I don't think #62 quite does it. If I generate with an empty extension now, it will always generate the file with a trailing "."

`codeGenerator.createNewFile("", "test.TestFile", "")` will write a file called `test.TestFile.`

**Comment by neetopia** [comment]
Can you check if you are using the latest release binary? I tried with the [playground](https://github.com/android/kotlin/releases/download/1.4-M1-dev-experimental-20200716/playground-1.4-M1-dev-experimental-20200716.zip) in the latest release and changed TestProcessor.kt#L24 to `codeGenerator.createNewFile("", "test.TestProcessor", "")`  and it can generate the file without trailing period.

**Comment by ZacSweers** [comment]
Yes I am using the latest release. Just pushed my work to here: https://github.com/ZacSweers/moshi-sealed/pull/25

Relevant code is in AutoServiceSymbolProcessor. If you change the createNewFile code there to just use the raw resource name and run the corresponding AutoServiceSymbolProcessorTest, you should be able to reproduce the issue

**Comment by ZacSweers** [comment]
Nevermind, I've figured this out. The problem was that the test was using the version of ksp that kotlin-compile-testing depended on, which was still the older version. Updated the PR now with them manually set and it works 👍

**Comment by neetopia** [comment]
I submitted a [PR](https://github.com/tschuchortdev/kotlin-compile-testing/pull/54) for updating dependency in kotlin-compile-testing hopefully this will be updated in next version.
